# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ralph Welborn
phone: +1 (415) 497-9641
email: ralph@capimpact.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.topplebook.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  topple

google_analytics: UA-120812862-1

# this is a reference to our AWS API Gateway, it uses a Lambda function to verify the Captcha submission, and then
# if success will send a notification to Simple Notification System in AWS.
#dd
# usage: <form action="{{ site.contact_form.action_url }}">
contact_form:
  action_url: https://ilopipx3s7.execute-api.us-west-2.amazonaws.com/prod/api

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-bootstrap-sass
  - jekyll-sitemap

sass:
  style: :compressed

# add fonts etc from bootstrap gem
bootstrap:
  assets: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/
  - README.md
